Nmasked_index: ''
SNPfile: ''
VCFfile: ''
allele_mode: null
baseDir: /home/ferrari/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes
bowtie_opts: null
bw_binsize: 25
cluster_configfile: null
cluster_logs_dir: /data/manke/group/ferrari/PhD_project/reference_datasets/Ferrari_mESC-iNPC_DMSOvsEPZ_fullEpigenomes_MERGED/output_DNA-mapping_snakepipe_mESC/cluster_logs
configfile: null
createDAG: false
dedup: false
downsample: null
ext: .fastq.gz
fastqc: true
fragment_length: 200
gcbias: false
genome: mm10
indir: /data/manke/group/ferrari/PhD_project/reference_datasets/Ferrari_mESC-iNPC_DMSOvsEPZ_fullEpigenomes_MERGED/fastq_mESC
insert_size_max: 1000
local: false
mapping_prg: Bowtie2
mapq: 5
mate_orientation: --fr
max_jobs: 10
mode: mapping
notemp: false
outdir: /data/manke/group/ferrari/PhD_project/reference_datasets/Ferrari_mESC-iNPC_DMSOvsEPZ_fullEpigenomes_MERGED/output_DNA-mapping_snakepipe_mESC
pipeline: dna-mapping
plot_format: png
properpairs: false
qualimap: false
reads:
- _R1
- _R2
snakemake_options: --use-conda --conda-prefix /home/ferrari/anaconda3/envs
strains: ''
tempdir: /data/extended/
trim: true
trim_options: null
trim_prg: trimgalore
verbose: false
workingdir: /data/manke/group/ferrari/PhD_project/reference_datasets/Ferrari_mESC-iNPC_DMSOvsEPZ_fullEpigenomes_MERGED/output_DNA-mapping_snakepipe_mESC
